# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: José Brest
title: QA Automation
email: josebrest@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: brestja
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: josé brest
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/mifoto2.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an automation and documentation engineer with experience in the field of data engineering. I specialized in this area through my academic training and my professional experience.
  Through my studies and work, I have gained a solid understanding of the tools and techniques necessary to automate processes and create clear and detailed documentation.
  I am willing to work hard and constantly learn to continue to improve in my field and contribute to the success of any team I am a part of.
  
content:
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Euler Tools
        link: https://euler.tools
        # link_text: boringcompany.com
        sub_title: API Documentation - Automation Developer
        caption: October 2021 - December 2022
        #quote: >
         # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            As an API Documentation Engineer, my main tasks include:

            Design and create clear and detailed documentation for APIs. This includes specifying the various endpoints, input and output parameters, error codes, and usage examples. Test and validate the APIs to ensure their stability and proper functioning. To do this I use tools like Postman and cURL to send requests and verify responses. Work closely with the API development team to understand and document its functionality and features. Keep your API documentation up to date and ensure it remains accurate and relevant as your code evolves.
            
            (Repositorios GitHub: [Automation](https://github.com/brestja/Automation/tree/main/N8N/Automations%20Demos), [Postman Collections](https://github.com/brestja/Postman_collections))
            
            As a Data Pipeline Automation and Documentation Engineer, my main tasks include:
            
            Design and create detailed documentation for the pipelines, this includes specifying the data flow, the different components, processes as well as the input and output parameters.
            Use tools such as Zapier, Integromat and n8n to automate data pipelines and ensure their correct operation.
            Work closely with the data engineering team to understand their needs and develop efficient and sustainable solutions.
            Keep data pipelines current and ensure their stability and efficiency as the volume and complexity of data increase.
            Create Telegram bots to facilitate access to data and interaction with the data engineering team.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Instituto AMEMT
        caption: 2020 - 2021
        sub_title: Desarrollo Front End - Vue.js
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          This course prepares me to have a solid foundation in the Javascript programming language as well as Html 5 and Css. Other technologies learned were Bootstrap and Vue.js.
  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Programa 111 Mil
        caption: 2017 - 2018
        sub_title: Programador
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
         Course given by the Ministry of Labor with the aim of training professionals in technology, covering topics such as: Algorithms, Object Oriented Programming (Java) and Database (MySql).                
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in automation some of my other interests and hobbies are:
      - Football
      - Chess
      - Músic

      Look at this cool image  
      ![N8N](/brestja.github.io/images/mifoto2.jpg "N8N")
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
